### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by barbier** [bluemanos/adminlte-bower#1]
Hi! I'm having some problems updating font-awesome. Please, could you update here, since FA it's a dependency from this project?

**Comment by bluemanos** [comment]
Thank you for report the problem.
I will update the libraries shortly. Please expect the update in 24 hours.

**Comment by bluemanos** [comment]
@barbier please apologize for waiting another day.

I just pushed 2.2.1 release - https://github.com/bluemanos/adminlte-bower/releases/tag/2.2.1
Let me know if everything are all right.

For future problem with library version - fill free to create PR :)
